### ISSUE TITLE
Path towards v1.1

### ISSUE THREAD

**Issue by alexander-held** [iris-hep/analysis-grand-challenge#162]
Prepare a v1.1 tag, which will correspond to the v1 analysis task. The task will **not** change. We presumably will branch off of v1.0.0 for this.

cc @eguiraud for related discussions

- [x] backport #149 and provide updated histogram references
  - done via #170
- [x] change histogramming: save histograms in binning as provided by coffea output, subsequently re-bin via cabinetry (https://github.com/scikit-hep/cabinetry/issues/412)
  - we declare this as "not affecting analysis task" as the binning used in the histograms is not explicitly specified, just implicitly starts to look like this now due to the functionality of the histogram validation
  - done via #165
- [x] port a fix for #131 which affects v1.0.0, so this is currently a (known) bug in that implementation that has since been fixed via `correctionlib` (we probably want some simpler one-off fix, as there will be no additional development on v1.* following this presumably)
  - done via https://github.com/iris-hep/analysis-grand-challenge/pull/163
- [x] fix cabinetry binning labels in config (this also should go into `main` after #158)
  - done for v1 via #165

Moving forward: major versions are distinct analysis tasks, minor/patch reserved for implementations.

**Comment by alexander-held** [comment]
We should also update the lower bound when re-binning, as that currently does not align with existing bin edges
```python
all_histograms[120j::hist.rebin(2), "4j2b", "ttbar", "nominal"]
```
This should be equivalent to `110j` (which is a bin boundary).

**Comment by alexander-held** [comment]
v1.1 is now released: https://github.com/iris-hep/analysis-grand-challenge/releases/tag/v1.1.0
