### ISSUE TITLE
User experience and performance improvements for pipeline demonstrator

### ISSUE THREAD

**Issue by alexander-held** [iris-hep/analysis-grand-challenge#64]
This collects various user experience and performance related aspects that the [CMS Open Data pipeline demonstration](https://github.com/iris-hep/analysis-grand-challenge/blob/ec5184fb65bdc96a3d8ff1ac00e7fc8a8f399213/analyses/cms-open-data-ttbar/coffea.ipynb) at the AGC 2022 workshop revealed.

# User experience

### ServiceX+`coffea`
- [ ] schema configuration with ServiceX processors in coffea
- [ ] naming transformations https://github.com/ssl-hep/ServiceX/issues/407
- [ ] understand differences between `auto_schema` and AGC schema with similarly named columns https://github.com/CoffeaTeam/coffea/issues/665
- [ ] `auto_schema` for non-jagged columns https://github.com/CoffeaTeam/coffea/issues/664
- [ ] non-async method to run ServiceX processor for easier debugging (ideally, `NanoEventsFactory.from_root`-like method)
- [ ] single-letter error messages https://github.com/CoffeaTeam/coffea/issues/666

### ServiceX
- [ ] it can take a long time for transforms to report how many files are to be processed in total

### `coffea`
- [ ] metadata caching https://github.com/CoffeaTeam/coffea/issues/662
- [ ] objects changing in surprising ways in systematic variations https://github.com/CoffeaTeam/coffea/issues/661
- [ ] allow attaching per-object systematic variations to the full event (to enable running over copies of events)? not great for performance, but convenient for usability
- [ ] weight-based systematics that use object properties but are attached to events https://github.com/CoffeaTeam/coffea/issues/667

# Performance

### ServiceX+`coffea`
- [ ] dask scaling https://github.com/CoffeaTeam/coffea/issues/611

### ServiceX
- [ ] DID finder becomes a bottleneck when running over a large amount of files

### `servicex-databinder` approach
- [ ] avoid bottleneck with file conversion / copying (feed data straight to Skyhook?)

**Comment by ekauffma** [comment]
Validation model which causes notebook to crash when getting post-fit prediction (`cabinetry.model_utils.prediction(model, fit_results=fit_results)`: https://gist.github.com/ekauffma/b9fcbba5bb6f1ba411b6be37d8586db6
