### ISSUE TITLE
Benchmarking epic

### ISSUE THREAD

**Issue by alexander-held** [iris-hep/analysis-grand-challenge#79]
This gathers points related to performance and functionality for benchmarking.

- [ ] UChicago dev instance: `FileNotFoundError` when running over local files ([reproducer](https://gist.github.com/alexander-held/667932a583c9fb3aa3edd88067c77435))
- [ ] UChicago prod instance: `KilledWorker` exception at scale (reproducer: default notebook with `N_FILES_MAX_PER_SAMPLE>=1000`) 
- [ ] scaling beyond ~50 workers at UNL
- [ ] `dask.distributed` scaling behavior (reproducer below): differs per site, see occasionally long tails where the last few tasks do not get picked up for a long time, and workers only process a few tasks sometimes while there are still tasks remaining

`dask.distributed` setup for simple scaling tests:
```python
import time
from dask.distributed import Client, progress

client = Client("tls://localhost:8786")

def do_something(x):
    time.sleep(5)
    return x

x = client.map(do_something, range(1000))
progress(x)
```
