### ISSUE TITLE
Merge strategy for recent changes

### ISSUE THREAD

**Issue by alexander-held** [iris-hep/analysis-grand-challenge#99]
the first two can be flipped

- [X] jupytext #92
- [x] ServiceX update #96 (once relevant deployments are confirmed to be available everywhere)
- [X] ServiceX update ported to ttbar notebook (= ACAT + improved ServiceX pipeline) #100
- [X] Improved ServiceX queries (all datasets in parallel) #107
- [x] update `requirements.txt` to reflect ServiceX client version required #112 -> **then tag v0.2** -> [v0.2.0](https://github.com/iris-hep/analysis-grand-challenge/releases/tag/v0.2.0)
- [x] NanoAOD switch #102 (cc @ekauffma) -> **then tag v1.0** (= v0.2 but with NanoAOD)  -> [v1.0.0](https://github.com/iris-hep/analysis-grand-challenge/releases/tag/v1.0.0)
    - no analysis logic changes (e.g. new cuts, x-sec values), these will be introduced after the tag on the way towards v2, we should also track them in a text document to more easily update other AGC implementations

cc @oshadura

**Comment by alexander-held** [comment]
With the release of [v1.0.0](https://github.com/iris-hep/analysis-grand-challenge/releases/tag/v1.0.0) this is now all completed.
